app:
  name: "@project.artifactId@"
  version: "@project.version@"

server:
  contextPath: "/publisher"
  port: 8080

spring:
  rabbitmq:
    host: "localhost"
    port: "5672"

queueConfig:
  exchangeName: "x_dochub"
  queueNameList:
    - "q_dev_boop"
    - "q_dev_botm"
    - "q_dev_bods"

