app:
  name: "@project.artifactId@"
  version: "@project.version@"

spring:
  rabbitmq:
    host: "localhost"
    port: "5672"
    listener:
      simple:
        acknowledge-mode: manual


rabbitmqSubscription:
  boop-queue: "q_dev_boop"
  botm-queue: "q_dev_botm"
  bods-queue: "q_dev_bods"
